{{- if and .Values.rbac.enabled (not .Values.rbac.namespaced) -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "microservice-friendslist.fullname" . }}-clusterrole
  labels:
    {{- include "microservice-friendslist.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups:
      - extensions
    resourceNames:
      - {{ template "microservice-friendslist.fullname" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end -}}
{{- end -}}
